### ISSUE TITLE
Add a proper readme file.

### ISSUE THREAD

**Issue by Procoder16** [AOSSIE-Org/Monumento#144]
Add a proper readme file describing about the project in details and also the guidelines for setting up the entire project.

**Comment by Procoder16** [comment]
@jddeep Kindly assign this issue to me. I am setting up the project and document each and everything nicely to make a perfect readme

**Comment by Tejwant12** [comment]
@jddeep I modified the changes of readme.md file of monumento kindly check the PR and assign me this project I would love to work on it.

**Comment by mdmohsin7** [comment]
These changes have been merged through the  #156  PR. Thank you for the contribution.
