### ISSUE TITLE
Gradle Build Fail

### ISSUE THREAD

**Issue by mayank0rajput** [AOSSIE-Org/Monumento#155]
There is a file missing in 'monumento_module/.android/include_flutter.groovy' which setting.gradle is unable to access.
In setting.gradle , line number 8 there is use of this file but unable to find this file so android studio is unable to build this.

**Comment by JA-26-01** [comment]
> 

I am facing the same issue

**Comment by mdmohsin7** [comment]
This has been fixed in the `develop` branch. Thank you for opening an issue.
