### ISSUE TITLE
Incorrect colors in Places Nearby section

### ISSUE THREAD

**Issue by mdmohsin7** [AOSSIE-Org/Monumento#177]
The colors for the chips in the `Places Nearby` section do not match the theme of the app

<img width="685" alt="Screenshot 2024-09-01 at 3 06 32 PM" src="https://github.com/user-attachments/assets/9e2fc63b-35f3-4483-97a1-07f7adf4c7f1">

Ideally the colors should match the theme.

**Comment by Bhavd33p** [comment]
Hey can u assign this to me ? @mdmohsin7

**Comment by mdmohsin7** [comment]
> Hey can u assign this to me ? @mdmohsin7

Assigned!
