### ISSUE TITLE
Improve setup docs

### ISSUE THREAD

**Issue by mdmohsin7** [AOSSIE-Org/Monumento#182]
### 🐛 Describe the bug

The setup documentation currently refers to creating a `.dev.env` file, but the project actually uses a `.env` file. Additionally, there are no mentions of the APIs being used or explanations of why they are needed.

Update the documentation to accurately reflect details about the `.env` file and the API keys

**Comment by lakshyasarve** [comment]
Hi can I please work on this issue?
i will make sure to include all the necessary details about onboarding and project details in the documentation.

**Comment by mdmohsin7** [comment]
Assigned @lakshyasarve

**Comment by lakshyasarve** [comment]
I'm done with #188. Could you please check
