### ISSUE TITLE
Setup Flutter Gen to manage assets 

### ISSUE THREAD

**Issue by mdmohsin7** [AOSSIE-Org/Monumento#184]
Currently the code uses directly the asset path strings which are prone to a lot of issues (causing issues if that asset is deleted etc).
<img width="426" alt="Screenshot 2024-12-06 at 2 30 04 PM" src="https://github.com/user-attachments/assets/d22f5d4a-1957-42ca-89e7-588549dc5b51">

Use `flutter_gen` package to manage the assets paths
https://pub.dev/packages/flutter_gen

**Comment by lakshyasarve** [comment]
Hi, can I please work on this issue?

**Comment by kareemabdeen** [comment]
I am done with #183, Can you please assign this issue to me ?
@mdmohsin7

**Comment by mdmohsin7** [comment]
Assigned @kareemabdeen

**Comment by kareemabdeen** [comment]
dn can you please review #186

**Comment by kareemabdeen** [comment]
Dn can you please review ? #186  
@mdmohsin7
