### ISSUE TITLE
Unable to Fill Password Text Field Without Dismissing Keyboard in Create Account View 🐛

### ISSUE THREAD

**Issue by kareemabdeen** [AOSSIE-Org/Monumento#187]
### Steps to Reproduce the bug 🐛:

1. Open the app and navigate to the **Create Account** screen.  
2. Fill in the **Name**, **Username**, and **Email** fields.  
3. Attempt to scroll to the bottom and tap on the **Password** text field while the keyboard is still active.  
4. Try to enter text into the **Password** field.  

**Observed Behavior:** The **Password** field cannot be accessed or filled unless the keyboard is dismissed first.

https://github.com/user-attachments/assets/1efc10da-ddf9-43a5-a797-f30adcdb46e5

**Comment by kareemabdeen** [comment]
Can you please assign this issue to me ?@mdmohsin7

**Comment by mdmohsin7** [comment]
Assigned @kareemabdeen

**Comment by kareemabdeen** [comment]
I have completed work on this issue #186 using your suggested edits. Please review it. Afterward, I will rebase these changes with the current working branch to avoid conflicts and push it to review @mdmohsin7

**Comment by kareemabdeen** [comment]
I have completed work on this issue https://github.com/AOSSIE-Org/Monumento/pull/186 using your suggested edits. Please review it. Afterward, I will rebase these changes with the current working branch to avoid conflicts @mdmohsin7

**Comment by kareemabdeen** [comment]
I'm done with it here #189. Could you please check? @mdmohsin7
