### ISSUE TITLE
Images in Feed have weird grey background

### ISSUE THREAD

**Issue by mdmohsin7** [AOSSIE-Org/Monumento#191]
Images in Feed have weird grey background if the images don't have the same resolution as that of the box. Make images cover the exact box size

<img width="675" alt="Screenshot 2024-12-11 at 9 00 58 PM" src="https://github.com/user-attachments/assets/9c98b294-cf1c-4fff-a893-38f8847fb103" />

**Comment by lakshyasarve** [comment]
could you please assign this issue to me?

**Comment by priyanshu9899** [comment]
i would like to work on this

**Comment by sumaya-786** [comment]
can you please assign it to me

**Comment by mdmohsin7** [comment]
Assigning @sumaya-786 as @lakshyasarve already has an issue assigned!

**Comment by sumaya-786** [comment]
I've submitted a PR (#1) that addresses this issue. Please review it when you have time.
Merge pull request https://github.com/sumaya-786/Monumento/pull/1 from sumaya-786/color

**Comment by Vardhan-ysh** [comment]
Hi, I want to work on this issue. Can I be assigned to this.

**Comment by mdmohsin7** [comment]
Assigned @Vardhan-ysh

**Comment by Vardhan-ysh** [comment]
@mdmohsin7 can you review the changes.
