### ISSUE TITLE
Add Device Preview for Enhanced Responsiveness

### ISSUE THREAD

**Issue by kareemabdeen** [AOSSIE-Org/Monumento#193]
### 🚀 The feature

Integrate Device Preview into the project to enhance responsiveness and ensure the app provides an optimal user experience across a wide range of devices and screen sizes. This feature will allow developers to preview and test the app's appearance and behavior directly in the development environment, simulating various devices, orientations, and resolutions.

By enabling seamless testing and responsiveness improvements, this feature will ensure the app adapts beautifully to mobile, tablet, and desktop screens, reducing reliance on physical devices and streamlining the development process.

### Motivation for the Proposal

While navigating through the app, I noticed UI issues like **content overflow** and misaligned elements. These problems often show up on certain devices or screen sizes but not others, making them hard to catch without testing across multiple devices.

For example:
- A layout might work fine on a large screen but break on smaller screens.
- Issues might appear on mobile but not on tablets or desktops.

Adding **Device Preview** will:
- Help simulate different devices and screen sizes during development.
- Catch and fix UI issues early.
- Ensure a consistent, responsive experience across all devices.

For example, while working on issue #187 a few days ago, I resolved a specific UI problem. However, while navigating through the app afterward, I discovered that several other pages have similar issues. I plan to address these issues later, in sha'Allah.

**Comment by kareemabdeen** [comment]
Iam dn with #192 , can you please assign it to me ? @mdmohsin7

**Comment by Vardhan-ysh** [comment]
Hi, I would like to work on this issue. Can I be assigned this?

**Comment by mdmohsin7** [comment]
Is device preview a package? @kareemabdeen

**Comment by kareemabdeen** [comment]
Yes, Device Preview is a package in Flutter. It allows developers to preview and test their apps on different devices, screen sizes, and orientations during development. You can find it on pubdev:https://pub.dev/packages/device_preview
@mdmohsin7

**Comment by mdmohsin7** [comment]
Makes sense! Pls go ahead @kareemabdeen

**Comment by mdmohsin7** [comment]
Assigned @kareemabdeen as he proposed this change. @Vardhan-ysh pls feel free to open other issues (fixes or improvements) or pick existing unassigned ones.

**Comment by kareemabdeen** [comment]
Iam dn with this issue in #197 PR, we can close it now 
@mdmohsin7
