### ISSUE TITLE
Incorrect navigation bar on tab size view

### ISSUE THREAD

**Issue by mdmohsin7** [AOSSIE-Org/Monumento#194]
The navigation bar isn't when I resize the app to tab layout

https://github.com/user-attachments/assets/ae9705fe-014d-4d59-97cf-0c5cc2794659

**Comment by lakshyasarve** [comment]
Could you please assign this issue to me ?

**Comment by HelloSniperMonkey** [comment]
hey @mdmohsin7 can you please assign this issue to me i have worked on flutter before

**Comment by nidhaahmed** [comment]
Hey @mdmohsin7 I believe I can fix this issue... Can you assign this to me

**Comment by nidhaahmed** [comment]
Hey @mdmohsin7 I believe I can fix this issue... Can you assign this to me

**Comment by mdmohsin7** [comment]
Assigning @HelloSniperMonkey since @lakshyasarve already has an issue assigned. @nidhaahmed pls feel free to pick other newly added issues or open new issues (bug fixes or improvements)
