### ISSUE TITLE
Add heading for Local Experts

### ISSUE THREAD

**Issue by mdmohsin7** [AOSSIE-Org/Monumento#195]
Currently there's no heading or anything which tells that the listed people are `Local Experts`. Add a heading for it.
<img width="423" alt="Screenshot 2024-12-16 at 1 53 05 PM" src="https://github.com/user-attachments/assets/0adcbd81-8cba-4cc8-92e4-34ff377c86f7" />

It should be similar to the `Places Nearby` heading which has a text and then a divider to separate the heading and the items

<img width="352" alt="Screenshot 2024-12-16 at 1 54 42 PM" src="https://github.com/user-attachments/assets/58de3c37-5ec5-47bd-b780-dae057e8060f" />

**Comment by kareemabdeen** [comment]
Could you please assign this to me? I have completed all the previously assigned issues. @mdmohsin7

**Comment by mdmohsin7** [comment]
Assigned @kareemabdeen

**Comment by kareemabdeen** [comment]
I think this already exists  , 
as There is a Heading for list of **local  Guides and experts**    @mdmohsin7 
![photo_2024-12-16_21-05-33](https://github.com/user-attachments/assets/4a89d1b1-a76b-412f-9a57-1a2e3d80505f)

**Comment by mdmohsin7** [comment]
Can you pls check and confirm if it exists when building for web as well @kareemabdeen

**Comment by kareemabdeen** [comment]
It seems not appearing in the desktop view. Insha'Allah, I will work on fixing this.

**Comment by kareemabdeen** [comment]
Dn , please check #209 PR @mdmohsin7
