### ISSUE TITLE
Empty env file exception unhandled

### ISSUE THREAD

**Issue by abhinavs1920** [AOSSIE-Org/Monumento#211]
### 🐛 Describe the bug

# Empty `.env` File Exception Unhandled

## **Description**  
When loading environment variables from a `.env` file, the application throws an unhandled exception when encountering issues with the file. This occurs in several scenarios:  
- Empty `.env` file  
- Incorrect UTF encoding format  
- Malformed `.env` file content  
- Missing `.env` file  

This exception is currently unhandled in the codebase, causing the application to crash instead of gracefully handling these common scenarios.

---

## **Steps to Reproduce**  
1. Create any of these test cases:  
   - **Case 1**: Empty `.env` file (create an empty file)  
   - **Case 2**: Incorrect UTF encoding  
   - **Case 3**: Malformed content  
2. Run the application  
3. Observe the unhandled exception  

---

## **Current Behavior**  
The application crashes with an unhandled exception when encountering these `.env` file issues.  

---

## **Expected Behavior**  
The application should:  
1. Detect and validate the `.env` file before attempting to read.  
2. Provide meaningful error messages for each failure case.  
3. Handle the exception gracefully with appropriate fallback behavior.  
4. Log the specific issue for debugging purposes.  

---

## **Error Message**  
![image](https://github.com/user-attachments/assets/32b87bee-ea90-4501-9272-f06382315ca6)

---

## **Suggested Solution**  
Implement proper error handling for `.env` file operations:  
- Validate file existence  
- Check file encoding  
- Verify file content format  
- Provide meaningful error messages  
- Add fallback mechanisms for missing/invalid configurations  

---

**Comment by abhinavs1920** [comment]
Can I work on this issue?
Thanks!

**Comment by mdmohsin7** [comment]
Assigned @abhinavs1920

**Comment by abhinavs1920** [comment]
I have created the PR related to the above issue. Can you please check? #215 
@mdmohsin7 
Thanks!!
