### ISSUE TITLE
Inconsistent/Irrelevant AppBar Text in User Connection Page

### ISSUE THREAD

**Issue by navaneeth0041** [AOSSIE-Org/Monumento#214]
### 🚀 The feature

The AppBar in the user connection page (followers/following view) should display either dynamic content based on the active tab in the profile page or the username of the user, instead of showing a static "Post" text alongside the back icon.

![Screenshot_20241224_202120](https://github.com/user-attachments/assets/a74d65e6-fffe-4b4b-aba6-aa02d9a6ba20)

### Motivation, pitch

I'm working on improving UI consistency in the profile section. Currently, when viewing a user's connections (followers/following) from any profile tab including bookmarks, the AppBar displays an irrelevant "Post" text. This creates confusion and breaks the expected UI flow. The text should either reflect the current context in the previous profile page or show the username of the user.

**Comment by navaneeth0041** [comment]
@mdmohsin7 I would like to work on this issue.

**Comment by mdmohsin7** [comment]
Assigned @navaneeth0041
